### ISSUE TITLE
Not having responsive UI

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/techous.github.io#29]
**Describe the bug**
This website doesn't have Reponsive UI. Background image is unadjusted.

**To Reproduce**
1. Go to stylesheet and improve background image size.

**Expected behavior**
Content remains in position.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser All

**Comment by anarchymonkey** [comment]
We are trying to improve the quality of the site , help as much as possible. :+1:

**Comment by anarchymonkey** [comment]
This was a major issue , thank you for solving it. :+1:
