### ISSUE TITLE
Footer copyright is not updated

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/techous.github.io#37]
**Describe the bug**
The copyright information is not updated for 2019.

**To Reproduce**
1. Update the footer in the code.

**Expected behavior**
The copyright should be updated as © 2019 Copyright: techOus Organization instead of © 2018 Copyright: techOus Organization

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by GauravWalia19** [comment]
I am working on this issue.

**Comment by anarchymonkey** [comment]
Thank you.
