### ISSUE TITLE
Phone UI is not correct.

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/techous.github.io#38]
**Describe the bug**
Phone UI is not correct event though website is responsive. Website is scrolled horizontally which should not be allowed. Also see the footer in the screenshots it contains unneccessary image.

**Screenshots**

![Screenshot from 2019-06-15 11-48-21](https://user-images.githubusercontent.com/29369199/59547920-42b26580-8f64-11e9-9896-6ac8b9062a00.png)

![Screenshot from 2019-06-15 11-48-26](https://user-images.githubusercontent.com/29369199/59547925-52ca4500-8f64-11e9-8985-921b4acdcf65.png)

**To Reproduce**
1. Update the styles.

**Expected behavior**
Phone UI should not be scrolled horizontally. Plus side image color should be present in Phone UI.

**Smartphone (please complete the following information):**
 - Device: Xiomi Mi note 5
 - OS: Android
 - Browser Chrome

**Comment by anarchymonkey** [comment]
custom @media tags are required, please submit a pull request stating the before mentioned fixed. 
Thank you, 
Happy developing.

**Comment by GauravWalia19** [comment]
I am working on this fix.
